### ISSUE TITLE
When emm386 is loaded, log is flooded with "gate descriptor is not valid" messages

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#107]
Not sure if it is bug or not, but definitely a problem.
When I boot DOS 6.22 with `emm386.exe` specified in `config.sys`, Bochs starts lagging and flooding logs with messages like
```text
01104191449e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x1a)
01104191721e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x16)
01104191904e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x16)
01104192051e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x1a)
01104192241e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x16)
01104192433e[CPU0  ] interrupt(): gate descriptor is not valid sys seg (vector=0x28)
```
IPS drops from 75M to 0.09M (when logging to console, `-`) or 16M (when logging to `nul`).

Files needed to reproduce this problem are in archive [dos_emm.zip](https://github.com/bochs-emu/Bochs/files/13063367/dos_emm.zip).

Version: f455fa87e42eccbccf467e479183ed26605c8755.

**Comment by stlintel** [comment]
try 

error: action=report, cpu=ignore

usually this error have meaning - this means the interrupt gate description is broken and usually it is developer problem.
I am wondering if DOS 6.22 was just broken because I am almost sure about this particular CPU code to be correct.

does it boot / work well if no logging messages ?

**Comment by Vort** [comment]
> does it boot / work well if no logging messages ?

Looks like so.
with `error: action=report, cpu0=ignore` IPS is at ~50M, which is good.

![image](https://github.com/bochs-emu/Bochs/assets/1242858/4b219447-1fb9-4ecf-9112-208b34cc1844)

> I am wondering if DOS 6.22 was just broken

I don't know why it was made in a such way.
Maybe there was a reason, or maybe just mistake.

So what is the solution?
To recommend people disabling CPU logs before using `emm386.exe`?

**Comment by stlintel** [comment]
Yes, I have no other idea. Welcome to any suggestion.
Today I tried to print  BX_ERROR before each fault like <#GP> here in order to provide enough information for people doing home-made OS development and debugging. This indicates that they made smth wrong. Till now I didn't have case when commercial software does smth wrong like this ...

**Comment by Vort** [comment]
It is strange that `emm386.exe` does something wrong and works correctly at the same time.
I'm thinking about possibilities of using some undocumented features by developers.
But checking such hypothesis requires very deep dive into history.
Maybe some books exists which describe how emm386 works.
Also I saw open source equivalents like [Jemm386](https://github.com/Baron-von-Riedesel/Jemm).
Probably testing and learning how it works may give clues.

**Comment by Vort** [comment]
I tested more binaries:

Jemm386 5.79 - no problem
QEMM 9.0 - no problem
EMM386 4.20.06X (from DOS 5.0) - errors
EMM386 4.49 (from DOS 6.22) - errors
EMM386 4.95 (from win98) - errors

So it is definitely possible to make memory manager without such problems and most likely MS versions have bug.
I'm closing this report. If anyone have more information or solutions - it can be reopened.
