### ISSUE TITLE
Shaking text in Commander Keen 5

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#114]
Text, which is displayed after starting Commander Keen 5, should not have horizontal movement.

Similar problem also occurs with VirtualBox 6.1.36.
However, VMware Workstation 12.5.2 shows animation correctly:

https://github.com/bochs-emu/Bochs/assets/1242858/05187fc6-cd59-4592-84f4-0f60d392f79e

Version: c48a50141b6ade6c6b0744280a598b55d906bb9e

**Comment by fysnet** [comment]
Doing a little research, this game was by id Software, same people who did Doom, Quake, and others. First "episodes" of Doom and Quake are freely available, and I found Commander Keen at https://dosgames.com/game/commander-keen-1-invasion-of-the-vorticons/.

So, I think it would not go against any rights or other legal issues if you were to provide a link to your image file. Either way, it would be for the sole purpose of trying to find the error in Bochs, rather than obtaining a legal or illegal copy of the game.
Therefore, if you feel it to be okay, please provide the image file for testing. Even if it is just enough of the game to show the error in question, meaning that you do not include any file that is not needed to show the intro, as shown in the video you posted. You could even remove access to image file after 24 hours.

If you feel that it would not be okay, that is your choice and I am okay with that too.

**Comment by Vort** [comment]
@fysnet, here it is: [keen5.zip](https://github.com/bochs-emu/Bochs/files/13197169/keen5.zip).
In case of complaints can be removed.

**Comment by fysnet** [comment]
It looks like to me the `BX_VGA_THIS s.attribute_ctrl.horiz_pel_panning` register is not implemented in graphics mode, and that is why this text "shakes".

The implementation probably loops though horizontally scrolling the screen to the left by 0 to 7 pixels by using this `horz pel` register, while at the same time displaying the text to the right 0 to 7 pixels. By doing this, it gives the effect of staying in place. 

i.e., the screen scrolls to the left -1 pixel while the text is written to the right +1 pixel, in a loop of 8 iterations.
```
i = 0;
while (i < 8) do
  horz_pel_reg = i
  display text at x+i,y
  i++;
done while
```

However, since this register is not implemented in Bochs' graphics modes, it doesn't work as expected.

This is just my opinion based on a bit of research on the subject and looking over `vgacore.cc`. I also found a reference that this game relies on this register to scroll, since it is a `side-scrolling` game.

I don't know the `vgacore.cc` code well enough to implement this register. Someone with more knowledge of the VGA and this code will need to add this function.

**Comment by vruppert** [comment]
Please try again with the latest code. I have tested the change with your ZIP and it looks okay to me.

**Comment by Vort** [comment]
> Please try again with the latest code. I have tested the change with your ZIP and it looks okay to me.

I still see shaking, but it goes away if I put `if (BX_VGA_THIS s.x_dotclockdiv2) x >>= 1;` before `if ((y <= lc) || ...`.
Not sure if it is correct fix however.

**Comment by vruppert** [comment]
You are right, that's the final fix. This game uses a screen width of 320 (half dot clock).

**Comment by Vort** [comment]
I confirm that game animation now works correctly with c525d9e5fc253b62fccd49c5e16daf12f68f8a95. Thank you.
