### ISSUE TITLE
Diagonal lines in JiZZ

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#124]
When running JiZZ, in some scenes diagonal lines appears, which should not be there.
For example in this one:
![bochs_jizz_artifacts](https://github.com/bochs-emu/Bochs/assets/1242858/614fc44d-33d8-41ef-8d9e-a736c5b3aac2)
This is how it should look like:
https://www.youtube.com/watch?v=iXgseVYvhek&t=93

Sadly I was not able to confirm proper behaviour with my real hardware because of video card incompatibility.

Test files: [jizz.zip](https://github.com/bochs-emu/Bochs/files/13280392/jizz.zip).

Version: 75d076b990a5a8198b6bf9a8ee1e43a37483eba3.

**Comment by Vort** [comment]
I've found similar problems with some images generated by Ultra Fractal 5.01.
This is how "Slope (Newton)" fractal looks like:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/cc876932-dcb3-479d-9138-cd2234675944)
![bochs_uf5](https://github.com/bochs-emu/Bochs/assets/1242858/b2d79fba-bbbd-4e05-9d73-2f41f9353fc1)

**Comment by Vort** [comment]
Newton fractal was valuable hint.
I've found open source program for its rendering:
https://www.codeproject.com/Articles/38514/The-beauty-of-fractals-A-simple-fractal-rendering
And it glitches in the same way:
![bochs_newton](https://github.com/bochs-emu/Bochs/assets/1242858/6d8abf01-e2ed-422b-82ef-b151712c7008)

**Comment by Vort** [comment]
Looks like I've found what is happening wrong here.
Function `atan2` is calculated incorrectly.
`atan2(-1, -1)` should produce `-2.35619449019234` result, but produces `-0.785398163397448` instead.
Here is test program made with FASM which works fine on real hardware and crashes in Bochs ([atan2.zip](https://github.com/bochs-emu/Bochs/files/13402892/atan2.zip)):
```asm
format PE GUI
finit
fld1
fchs
fld st0
fld st0
fpatan
fcom st1
fnstsw ax
test ah, 1
jnz l
int 3
l:
ret
```

**Comment by stlintel** [comment]
The SDM says:

`The FPATAN instruction returns the angle between the X axis and the line from the origin to the point (X,Y), where Y (the ordinate) is ST(1) and X (the abscissa) is ST(0). The angle depends on the sign of X and Y independently, not just on the sign of the ratio Y/X. This is because a point (−X,Y) is in the second quadrant, resulting in an angle between π/2 and π, while a point (X,−Y) is in the fourth quadrant, resulting in an angle between 0 and −π/2. A point (−X,−Y) is in the third quadrant, giving an angle between −π/2 and −π.`

i bet this "quadrant" story is not enforced correctly and Bochs sometimes returns value in wrong quadrant.
For example for FPATAN(-1,-1) it was supposed to be -3/4 pi but Bochs returned -1/4 pi
I bet the same could be for other arguments.
Anyway - pushed this "stupid" fix probably won't be affecting anything because it fixes only |y|=|x| and might be it is not enough.
Can you check ?

**Comment by stlintel** [comment]
I wrote unit test for all x87 transcendental instructions and they actually not that bad
FPATAN is the worst with potential error over hardware up to 16lsb.
But I don't see any case like FPATAN(-x,-x) which was terribly wrong.
So I believe the issue should be completely fixed. Can you confirm ?

**Comment by Vort** [comment]
> Can you check ?

All three programs now work correctly. Thank you.
