### ISSUE TITLE
BOCHS does not handle the RF bit of RFLAGS when VMEXIT.

### ISSUE THREAD

**Issue by lgj1107** [bochs-emu/Bochs#215]
(28.3.3 Saving RIP, RSP, RFLAGS, and SSP
With the exception of the resume flag (RF; bit 16), the contents of the RFLAGS register is saved into the
RFLAGS field. RFLAGS.RF is saved as follows:
.............................................
)
https://github.com/bochs-emu/Bochs/blob/167942816aa9847503c61993091edd2d90cdda42/bochs/cpu/vmx.cc#L2411

**Comment by stlintel** [comment]
What part of the 'as follows' is not like in HW ?
Do you have a test case as well ?
It seems like potential question could raise only around:

- If the VM exit is caused by an attempt to execute an instruction that unconditionally causes VM exits or one
that was configured to do with a VM-execution control, the value saved is 0
- For APIC-access VM exits and for VM exits caused by EPT violations, EPT misconfigurations, page-modification log-full events, or SPP-related events, the value saved depends on whether the VM exit occurred
during delivery of an event through the IDT:
• If the VM exit stored 0 for bit 31 for IDT-vectoring information field (because the VM exit did not occur
during delivery of an event through the IDT; see Section 28.2.4), the value saved is 1.
• If the VM exit stored 1 for bit 31 for IDT-vectoring information field (because the VM exit did occur
during delivery of an event through the IDT), the value saved is the value that would have appeared in
the saved RFLAGS image had the event been delivered through the IDT (see above).

But anyhow need a test case where Bochs doesn't meet the spec and detailed description of the scenario where it is wrong.

**Comment by lgj1107** [comment]
I only tested the case of EPT violations.

bochs：
![bochs](https://github.com/bochs-emu/Bochs/assets/3366897/4630440d-d80e-45e5-9c83-e41f7cb29f38)

i5-2400：

![i52400](https://github.com/bochs-emu/Bochs/assets/3366897/33bdaa05-9c6e-49fd-ab45-d9e2bf30b763)

test image：
[test1.zip](https://github.com/bochs-emu/Bochs/files/13917675/test1.zip)

**Comment by stlintel** [comment]
Test passes so github closed the issue automatically :)
I handled only some cases that were mentioned in the docs so more similar issue are still possible in other cases.
For example here:
If the VM exit is caused by an attempt to execute an instruction that unconditionally causes VM exits or one
that was configured to do with a VM-execution control, the value saved is 0

If you find any such case -> please open another issue.
Thanks
Stanislav
