### ISSUE TITLE
Wrong colors after resolution change with Voodoo 3

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#272]
Colors in Windows 95 with Voodoo 3 may become wrong during resolution change.

To reproduce this problem:
1. Start with resolution 800x600x16.
2. Change resolution to 1024x768x16.
3. Change resolution to 1024x768x8.

Green colors instead of black appear:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/eeb45b0f-e1a4-418b-85f6-a173d45ae0ad)

Version: 1ff88fdd.

**Comment by vruppert** [comment]
I need some more information, since I cannot reproduce it here. I'm using the latest Bochs code with VGA_MEM_FIX enabled and the latest LGPL'd VGABIOS. I don't know which driver version I have used for this installation, since I did it some years ago right after I managed to get Banshee and Voodoo3 basically working.

**Comment by Vort** [comment]
> I don't know which driver version I have used for this installation

Can be checked like so:

![image](https://github.com/bochs-emu/Bochs/assets/1242858/65c430c9-a557-4940-a455-c74178180703)

4.12.01.0666 corresponds to 1.07.00-WHQL version.

> I'm using the latest Bochs code with VGA_MEM_FIX enabled

I tested with `VGA_MEM_FIX` and without it - does not matter.

> and the latest LGPL'd VGABIOS

I'm using latest `VGABIOS-lgpl-latest-banshee` as well (`4fc9c761`).

---

Are you sure that you changed resolution first (800x600 -> 1024x768) and bit depth next (16 -> 8)?

**Comment by vruppert** [comment]
I just had a look - I'm using the same driver version. I made the same steps as you did. The Windows 95 version number is 4.00.1111. Maybe someone else could repeat this test.

**Comment by Vort** [comment]
Same effect can be observed with Windows 98.
I made video just in case:

https://github.com/bochs-emu/Bochs/assets/1242858/e7bab472-c800-455e-a47d-0cc365295bd5

**Comment by Vort** [comment]
> My version of Win95 (4.00.1111) doesn't let me change the modes using the voodoo driver:

Look at discussion #180 - PCI bus should be installed manually before drivers can be installed.

**Comment by fysnet** [comment]
> Look at discussion #180 - PCI bus should be installed manually before drivers can be installed.

Curiosity has got me. From that PR:

> I know about the missing PCI bus after installing Win9x. Since the Bochs BIOS (as well as SeaBIOS) has only a stub for the PnP BIOS, it is not possible to get the list of installed devices.

With the new BIOS I just posted at #273, given it has more PnP support, I wonder if the PCI part is now fixed?

![bios_pci](https://github.com/bochs-emu/Bochs/assets/11790532/e7c43c61-ab0b-45ea-84a3-d427f0555be4)

Looks like it did. I didn't even notice that it had, or wasn't paying attention. :-)

I will look at the driver you mentioned and see if I can reproduce the error.

Thanks,
Ben

**Comment by fysnet** [comment]
I must have an old version of Win95. The Voodoo install wants IE 4.0+ and I don't even have that installed :-)
I think I have a supplement file somewhere to upgrade it. I will look.

**Comment by Vort** [comment]
> The Voodoo install wants IE 4.0+

It is possible to install driver without launching `.exe` files, by pointing OS manually to `driver9x` directory.
It is probably 3dfx Tools which needs IE, not driver by itself.

**Comment by fysnet** [comment]
What is your bochsrc.txt file lines for the voodoo3?
I have:
```
vgaromimage: file=$BXSHARE/bios/VGABIOS-lgpl-latest-banshee
vga: extension=voodoo3, update_freq=10
voodoo: enabled=1, model=voodoo3

pci: enabled=1, chipset=i440fx, slot5=voodoo
```
I point the OS to the `driver9x` folder as you specify, the driver is installed successfully.
I then go to the `settings` as shown in the first image you have above and Win95 states:

`Your display adapter is not configured properly. To correct the problem, click OK to start the Hardware Installation Wizard.`

I let it do it's thing. It finds the voodoo3 and says all is okay. I then go to `settings` again, and it allows me to  change to 1024x768x16bits, and then asks to restart.

When it comes back, it is not at 1024x768x16bits, and when I go to `settings` the `Your display adapter...` dialog shows up again.

**Comment by Vort** [comment]
> What is your bochsrc.txt file lines for the voodoo3?

```
vgaromimage: file="d:\Bochs-2.7\VGABIOS-lgpl-latest-banshee"
pci: enabled=1, chipset=i440fx, slot1=voodoo, slot2=ne2k
vga: extension=voodoo, update_freq=0, realtime=0, ddc=builtin
voodoo: enabled=1, model=voodoo3
```

There should be `extension=voodoo`, not `extension=voodoo3`.

**Comment by fysnet** [comment]
After changing the extension to `voodoo`, I can confirm the green instead of black.
![voodoo3](https://github.com/bochs-emu/Bochs/assets/11790532/17d4c58b-9031-45f2-bcfd-539297153bb5)
I can confirm that the voodoo driver does not install correctly if Win95 does not find a PCI bus. You either have to manually add it as you explain in #180, or use my new BIOS (#273) so that the PnP is used.
I also had to tell Win95 that the Monitor is a `SVGA 1024x768x16` first. Something I can add to the PnP part of the BIOS so this is already done.

Volker. You do have to follow the sequence of changing from 1024x768x16 to 1024x768x8. As the change is made, the whole screen flashes green for a split second, and everything that should be black is now green until you reset to another mode, or restart the emulation.

Since the black is probably the first entry in the 8-bit pallet and true green is the last part of an 8-bit pallet, can there be a buffer over run writing the green, which rolls over to the first of the pallet and writes a single entry to the now zero entry of the pallet? i.e.: your loop is one too many when writing the green pallet entries? Just a thought.

Thanks,
Ben

**Comment by vruppert** [comment]
Since I couldn't reproduce this issue on Linux, I tried it now on Windows and there it really exists. Then I tried the same image with the same setup on Linux and everything is fine. After restarting the Windows version the colors are correct again. The differences are the compiler (gcc on Linux / MSVC on Windows) and the gui (X11 on LInux / win32 on Windows). Now I can start to find out what's going on.

**Comment by vruppert** [comment]
Update: Now I made some save/restore tests on Windows. The saved data looks okay: voodoo_vga.vgacore.pel_dara shows RGB 0/0/0 for the first entry which is usually used for black. After restoring (tricky - see below) there is no light green anymore, but some other colors are wrong. After a small modification of the saved config I tried to restore from the same folder with the sdl2 gui and everything looked okay. Finally I tried with the win32 gui again, but compiled with gcc. It shows the same issues after restore as the MSVC build.

The restore function for Windows doesn't work with relative paths used in config unless I disable the recently added SetCurrentDirectory() call in win32config.cc. I think we need some kind of special directive in the saved config that points to the folder of the original bochsrc file. Something like that placed on top of config could be useful:

#path c:\path\to\saved\data

**Comment by Vort** [comment]
Relative paths are relative to something.
For system to work properly, this "something" must be clearly defined.

Support of relative paths is broken in many places, I think these problems deserve separate issue(s).
But base for absolute paths should be defined before making attempts to fix problems.

**Comment by Vort** [comment]
Most likely, problem is located in this code:
https://github.com/bochs-emu/Bochs/blob/abdbc52f2285cf7cc621ea8e43400311b0ac461f/bochs/gui/win32.cc#L1894-L1915

Performing `bitmap_info->bmiColors[256] = bitmap_info->bmiColors[0];` without checking if previous mode also was 16 bpp looks suspicious.

**Comment by vruppert** [comment]
I have also found this code, but I haven't tried to modify it yet. The win32 internal palette has 259 entries and the last 3 are the color masks for 16 bpp. In case of a bpp change they should be swapped with the first three ones. True color modes don't need all of this stuff. Since the Voodoo3 driver seems to use index 1 to 254 only, I guess index 1 should be black and in case of 16 bpp it is the green mask. I'll have a look what to do.

**Comment by vruppert** [comment]
I have now modified the code to skip this section if there is no bpp change. It would be better to have two different arrays, one with 256 entries for 8 bpp and one with 3 entries for 16 bpp to get rid of this swapping.

**Comment by Vort** [comment]
No problem appear anymore. I think this change is good for now. Thanks.
