### ISSUE TITLE
BXSHARE support is broken

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#295]
In my config files I use lines like this `vgaromimage: file="$BXSHARE\VGABIOS-lgpl-latest-banshee"`.
After some recent changes it no longer works: `could not look up environment variable 'BXSHARE'`.

I suspect e3274339 broke it.
> Please note that I don't know why the parameter was initially empty. Was
> this to catch a base/default parameter?

Yes:
![image](https://github.com/bochs-emu/Bochs/assets/1242858/5fb284b8-c904-4ded-85c7-77327e8300d8)

This is where installer stores path I guess.

Version: 1924cd4.

**Comment by vruppert** [comment]
I guess Ben wanted to split the install path and the BXSHARE location. If you modify it for your needs, the uninstaller might get confused and doing things you don't want to do. I have added a registry value called BX_SHARE_PATH to the installer of release 2.8, since I'm using a different folder for the development files and it works now without breaking the uninstaller.
Yesterday I tried to add an extension for the debugger gui to use an option like this "gui_debug:$BXSHARE", but it ends with a panic. I tried this on Linux, so it's a different issue. I think the variable handling needs to be reviewed.

**Comment by vruppert** [comment]
I'm sorry. I thought that I did it for the release, but it was afterwards. For compatibility we could add back reading the default value if BX_SHARE_PATH isn't set. I'll have at the code, since there is the other issue I found yesterday.

**Comment by vruppert** [comment]
Please try again after latest config.cc change.

**Comment by Vort** [comment]
110bb94 works good with and without `BX_SHARE_PATH`. Thank you.
