### ISSUE TITLE
How to change Bochs VBE Memory (Video Memory) to 8MB or lower or higher than 16 MB?

### ISSUE THREAD

**Issue by youself64github** [bochs-emu/Bochs#309]
Since default Bochs VBE Memory is 16 MB, but how can I change it to 8MB or lower or higher than 16 MB (Max 32 MB)?

**Comment by vruppert** [comment]
Currently the only way to change VBE video memory size is to set VBE_DISPI_TOTAL_VIDEO_MEMORY_MB in vga.h to the desired size before compiling Bochs. The VGABIOS should be able to use it, since the size in 64k units is stored in a readonly register. Adding a bochsrc option for the vram size seems to be possible.

**Comment by vruppert** [comment]
I have now added an option to change the VBE memory size. Valid choices are 4, 8, 16 and 32 MB (default is still 16 MB). The latest binary of the LGPL'd VGABIOS is required to make it work correctly.
