### ISSUE TITLE
No sound in Windows 9x with ES1370

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#336]
After I install drivers for ES1370 sound card on Windows 95 or 98, no sound appears.
Here are driver files which can be used for testing:
[es1370_win9x_4.05.1044.zip](https://github.com/user-attachments/files/16733472/es1370_win9x_4.05.1044.zip)

_(I tested this sound card with Windows XP as well, and it works fine there with default drivers)_

Version: 7260750

**Comment by vruppert** [comment]
I never tried the ES1370 with Windows 95, but I remember that it worked with Windows 98. For now I can only confirm that I also cannot hear sound. For further investigation, I switched the wavemode to 2 and specified a WAV output file. It segfaults when it should start playing sound. It seems to be a different issue, since it also happens with SB16. I remember that all this was working properly after the sound subsystem rewrite some years ago . Currently I have only a little time for Bochs, but I'll try to fix these issues ASAP.

**Comment by Vort** [comment]
> but I remember that it worked with Windows 98

It means regression testing can be applied:
2.6.11 - good
2.7 - bad

**Comment by vruppert** [comment]
Saving state after booting Win98 pointed me to the right direction. The 'wave_vol' member is always 0 and with Bochs 2.7 the speaker volume control has been added. I did it based on the Linux driver for the ES1370, but I didn't notice that Win9x had no sound then. I don't know (yet) what happens when I adjust the volume controls there. As a quick and dirty hack you could change the reset value of 'wave_vol' to 0xffff. It would be better to find out how Win9x sets up the mixer.

**Comment by Vort** [comment]
Looks like I know where problems come from:
Win9x driver makes reads from address `0xc045`.
Datasheet states that Interrupt/Chip Select Status RegisterAddress 04H Addressable as longword only, but apparently this is not true and real hardware support unaligned reads as well.
I did not figured out yet how exactly port accesses are set up, but I guess `es1370_iomask` variable should be tuned.

**Comment by Vort** [comment]
Works good now. Thank you.

**Comment by vruppert** [comment]
Thanks, I expected something like that. Unimplemented byte reads return 0xff and in this special case it indicates "CODEC busy". That's why Win9x doesn't write to the mixer. I hope everything's okay now. BTW: The issues related to the "file" driver still exist.
