### ISSUE TITLE
No video playback in MegaMan X4 with Voodoo 3 (again)

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#337]
This issue is very similar to #231:
Game is started, no video is displayed.

Once fixed in #231, it was broken again later.

Here are results from regression testing:
19.05.2024 b76ead9 - good
25.05.2024 426bd50 - good
25.05.2024 244e35a - no image
31.05.2024 9264301 - no image
01.06.2024 12e7803 - bad
25.08.2024 0138ad4 - bad

**Comment by Vort** [comment]
Easier test can be done with my program [modeset.zip](https://github.com/bochs-emu/Bochs/files/14084454/modeset.zip). Same black screen appears.

**Comment by vruppert** [comment]
I can confirm this issue, but I have no quick solution for it. Since the whole display update code uses pointers, the address wrap condition leads to a segfault. In this special case the address wrap would happen within a scan line. The only way to fix this is to use an offset variable and always read from video memory this way: v->fbi.ram[offset & mask]. This may take some time, since I'm going on vacation tomorrow.

**Comment by Vort** [comment]
> In this special case the address wrap would happen within a scan line.

There is no address wrap in this case.
Otherwise there would be crashes and image corruptions.
320x200 mode uses `half_mode` and `double_width`, while this check does not take it into account:
https://github.com/bochs-emu/Bochs/blob/0138ad41144ac51753c9d93ec32eadffaaff29fc/bochs/iodev/display/voodoo.cc#L602

**Comment by vruppert** [comment]
Please try again with latest revision of voodoo.cc.

**Comment by Vort** [comment]
Video displays correctly again. Thanks.
![image](https://github.com/user-attachments/assets/2a969ab5-80f6-4030-befe-2ed4d9b502c2)
