### ISSUE TITLE
Key sticking when two Shifts are pressed

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#381]
When left Shift and right Shift keys are pressed simultaneously and released afterwards, Bochs behaves like one of these keys remains pressed.

Problem can be reproduced like this:
1. Start MS-DOS;
2. Type `qwe`;
3. Press left Shift + right Shift;
4. Type `rty`.

`qwerty` should appear, but `qweRTY` appears instead:
![bochs_shifts](https://github.com/user-attachments/assets/fad76d1a-a2bc-4456-b03b-6c6303c9ecb2)

Test files: [DOSSmall.zip](https://github.com/user-attachments/files/17644055/DOSSmall.zip)
Host OS: Windows 7
Version: 890cc3a

**Comment by vruppert** [comment]
I could reproduce this issue on Windows with the win32 and wx gui. The SDL gui on Windows and all guis available on Linux are not affected. When pressing a shift key Windows periodicly generates keypress events. After pressing second shift key it continues with keypress events of the second shift. After releasing both keys only the release event of the last detected key is generated. Since one of the release scancodes is missing then, the state of this shift key in the guest os remains as pressing. I'll have a look for a workaround in the affected guis.

**Comment by vruppert** [comment]
Please try again with latest win32.cc code.

**Comment by Vort** [comment]
Works good now. Thank you.
