### ISSUE TITLE
Incorrect update interval with Voodoo

### ISSUE THREAD

**Issue by Vort** [bochs-emu/Bochs#434]
Frames of splash animation, which is playing when glide-based programs are started in DOS, are displayed with incorrect timing.
It happens because of different update frequencies for VGA and Voodoo. In the following log, VGA frequency is at 10 Hz, while Voodoo frequency is at 29 Hz.

```
00118088904i[VOODOO] memory FIFO now enabled
00118093116i[WINGUI] dimension update x=640 y=480 fontheight=0 fontwidth=0 bpp=16
00118093116i[VOODOO] Voodoo output 640x480@0Hz
00118093116i[BXVGA ] Setting VGA update interval to 100000 (10,0 Hz)
00132341885i[VOODOO] Voodoo output 640x480@29Hz
```

Test files: [glidesplash.zip](https://github.com/user-attachments/files/18260189/glidesplash.zip).
Version: 42ae1e8

**Comment by vruppert** [comment]
Your test program does not initialize the video timing before turning on the vga override (640x480@0Hz). After an override change in vsync update mode set_update_timer() is called. Since the vertical frequency is 0 Hz at this point, a safe value of 10 Hz is used. A vertical frequency change in override mode is not handled yet. I'll have a look what to do.

**Comment by vruppert** [comment]
Now I have found a way to notify the vga core to update the interval. Please verify the new code with games using Voodoo1/2. The Banshee / Voodoo3 models should not be affected.

**Comment by Vort** [comment]
1. Animation now plays smoothly;
2. I tested Tomb Raider, Descent II and GTA - all work fine.

Thank you.
